###
GET http://localhost:8080/schema/
Accept: application/json

###
GET http://localhost:8080/schema/election
Accept: application/json

###
GET http://localhost:8080/schema/election/CastVote
Accept: application/json

###
GET http://localhost:8080/schema/election/ListOpenElections
Accept: application/json

###
POST http://localhost:8080/election/CommenceElection
Content-Type: application/json

{
  "ElectionID": "{{$random.uuid}}",
  "OrganizerUserID": "34fb3192-d5a0-4e68-83cd-b50a1c7946f4",
  "Name": "Where to Eat",
  "Description": "My gustatory elegance yearns for replenishment."
}

> {%
    client.global.set("election_id", response.body.meta.request.attributes.ElectionID);
%}

###
GET http://localhost:8080/election/ListOpenElections?SortBy=CommencedAt&SortDirection=descending&Page=1&ItemsPerPage=2
Accept: application/json

###
POST http://localhost:8080/election/MakeProposal
Content-Type: application/json

{
  "ElectionID": "{{election_id}}",
  "ProposalID": "{{$random.uuid}}",
  "OwnerUserID": "28cc5071-3855-4638-82f1-54f30245fe4e",
  "Name": "Cosmic Cravings",
  "Description": "Taste the galaxy in every bite."
}

> {%
    client.global.set("proposal_id", response.body.meta.request.attributes.ProposalID);
%}

###
GET http://localhost:8080/election/ListProposals?ElectionID={{election_id}}&Page=1&ItemsPerPage=2
Accept: application/json

###
GET http://localhost:8080/election/GetProposalDetails?ProposalID={{proposal_id}}
Accept: application/json

###
POST http://localhost:8080/election/CastVote
Content-Type: application/json

{
  "ElectionID": "{{election_id}}",
  "UserID": "9f32d3e2-6839-4164-99ca-24bb32a697f9",
  "RankedProposalIDs": [
    "{{proposal_id}}"
  ]
}

###
POST http://localhost:8080/election/CloseElectionByOwner
Content-Type: application/json

{
  "ID": "{{$random.uuid}}",
  "ElectionID": "{{election_id}}"
}

> {%
    client.global.set("command_id", response.body.meta.request.attributes.ID);
%}

###
GET http://localhost:8080/async-command-status/{{command_id}}?include_logs=true
Content-Type: application/json

###
GET http://localhost:8080/election/GetElectionResults?ElectionID={{election_id}}
Accept: application/json
