{
 "title": "CQRS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 Commands",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, round(increase(testapp_cqrs_command_bus_call_handle_duration_milliseconds_count[$__range]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(testapp_cqrs_command_bus_call_handle_duration_milliseconds_count[$__range])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(testapp_cqrs_query_bus_call_handle_duration_milliseconds_count[$__range])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, round(increase(testapp_cqrs_query_bus_call_handle_duration_milliseconds_count[$__range]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Command Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(testapp_cqrs_async_command_bus_call_handle_duration_milliseconds_count[$__range])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Dispatched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(testapp_cqrs_event_dispatcher_publish_success_total[$__range])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Async Commands",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, round(increase(testapp_cqrs_async_command_bus_call_handle_duration_milliseconds_count[$__range]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, round(increase(testapp_cqrs_event_dispatcher_publish_success_total[$__range]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Listener Executions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(testapp_cqrs_event_dispatcher_call_on_event_duration_milliseconds_count[$__range])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(testapp_cqrs_async_command_bus_enqueue_error_total[$__rate_interval]))",
     "legendFormat": "Async Command Bus - Enqueue"
    },
    {
     "expr": "sum(rate(testapp_cqrs_command_bus_call_handle_error_total[$__rate_interval]))",
     "legendFormat": "Command Bus - Handle"
    },
    {
     "expr": "sum(rate(testapp_cqrs_query_bus_call_handle_error_total[$__rate_interval]))",
     "legendFormat": "Query Bus - Handle"
    },
    {
     "expr": "sum(rate(testapp_cqrs_event_dispatcher_publish_error_total[$__rate_interval]))",
     "legendFormat": "Event Dispatcher - Publish"
    },
    {
     "expr": "sum(rate(testapp_cqrs_event_dispatcher_call_on_event_error_total[$__rate_interval]))",
     "legendFormat": "Event Subscriber - OnEvent"
    },
    {
     "expr": "sum(rate(testapp_cqrs_broker_publish_error_total[$__rate_interval]))",
     "legendFormat": "Broker - Publish"
    }
   ]
  },
  {
   "title": "Top 10 Event Listeners",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(10, round(increase(testapp_cqrs_event_dispatcher_call_on_event_duration_milliseconds_count[$__range]), 1))",
     "legendFormat": "{{cqrs_event_listener_type}}"
    }
   ]
  },
  { "title": "Command Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Command Bus - Call Handle - execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cqrs_command_type) (rate(testapp_cqrs_command_bus_call_handle_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Bus - Call Handle - Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_command_bus_call_handle_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{cqrs_command_type}}"
    }
   ]
  },
  { "title": "Async Command Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Async Command Bus - Call Handle - execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cqrs_command_type) (rate(testapp_cqrs_async_command_bus_call_handle_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Command Bus - Call Handle - Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_async_command_bus_call_handle_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{cqrs_command_type}}"
    }
   ]
  },
  { "title": "Query Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Query Bus - Call Handle - execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cqrs_query_type) (rate(testapp_cqrs_query_bus_call_handle_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Bus - Call Handle - Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_query_bus_call_handle_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{cqrs_command_type}}"
    }
   ]
  },
  { "title": "Event Dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Events Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_events_dispatched_total[$__rate_interval])",
     "legendFormat": "{{cqrs_command_type}}"
    }
   ]
  },
  {
   "title": "Broker Publish",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(testapp_cqrs_broker_publish_success_total[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(testapp_cqrs_broker_publish_error_total[$__rate_interval])) > 0",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Published Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_event_dispatcher_publish_success_total[$__rate_interval])",
     "legendFormat": "{{cqrs_event_type}}"
    }
   ]
  },
  {
   "title": "Broker Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "expr": "avg(sum by() (testapp_cqrs_broker_reconnected_total)) > 0",
     "legendFormat": "Reconnected"
    },
    {
     "expr": "avg(sum by() (testapp_cqrs_broker_disconnected_total)) > 0",
     "legendFormat": "Disconnected"
    }
   ]
  },
  { "title": "Event Subscriber", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Event Subscriber - Call OnEvent execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cqrs_event_listener_type) (rate(testapp_cqrs_event_dispatcher_call_on_event_duration_milliseconds_bucket[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Subscriber - Call OnEvent - Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(testapp_cqrs_event_dispatcher_call_on_event_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{cqrs_event_listener_type}}"
    }
   ]
  }
 ]
}