name: "Setup Go Project"
description: "Checks out repo, sets up Go, installs tools, and runs go generate"

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true
        cache: true

    - name: Configure Git for private modules
      run: git config --global url."https://${GH_TOKEN}@github.com/inklabs/cqrs".insteadOf "https://github.com/inklabs/cqrs"
      env:
        GH_TOKEN: ${{ secrets.CQRS_READ_TOKEN }}

    - name: Go Mod Download
      run: go mod download
      env:
        GOPRIVATE: github.com/inklabs/cqrs

    - name: Go Mod Verify
      run: go mod verify

    - name: Install Protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go and protoc-gen-go-grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install Python grpcio-tools
      run: |
        python3 -m pip install --upgrade pip
        pip install grpcio-tools

    - name: Go Generate
      run: go generate .
