name: Build
on:
  workflow_run:
    workflows: [ "Unit Tests" ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          gh-token: ${{ secrets.CQRS_READ_TOKEN }}

      - name: Get version
        id: vars
        run: echo "version=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT

      - name: Build
        run: ./build/build-release.sh ${{ steps.vars.outputs.version }}"

      - name: Update Latest Release
        id: gh_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && steps.vars.outputs.version || 'latest' }}
          name: ${{ github.ref_type == 'tag' && format('Release %s', steps.vars.outputs.version) || 'Latest Build' }}
          draft: false
          prerelease: ${{ github.ref_type != 'tag' }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Webhook
        run: |
          echo "Notifying service of release: ${{ steps.gh_release.outputs.html_url }}"
#          curl -X POST -H "Content-Type: application/json" \
#               -d '{"text":"New release available: '${{ steps.gh_release.outputs.html_url }}'"}' \
#               ${{ secrets.NOTIFY_WEBHOOK }}
