name: Unit Tests
on:
  push:
    branches: [ main ]
    tags: [ "v*" ]

jobs:
  call-setup:
    uses: ./.github/workflows/setup.yml
    with:
      CQRS_READ_TOKEN: ${{ secrets.CQRS_READ_TOKEN }}

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Go Test
        run: go test -v -count 1 -race -failfast ./...
