name: Unit Tests
on:
  - push
  - pull_request

env:
  GOPRIVATE: github.com/inklabs/cqrs

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Configure Git for private modules
        run: git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          GH_TOKEN: ${{ secrets.CQRS_READ_TOKEN }}
          
      - name: Go Mod Download
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate .

      - name: Go Test
        run: go test -v -race -failfast ./...
