name: Unit Tests
on:
  push:
    branches: [ main ]
    tags: [ "v*" ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go

      - name: Go Test
        run: go test -v -count 1 -race -failfast ./...
